import { test, expect } from '@playwright/test';
import * as XLSX from 'xlsx';

test('transfers, loan collection, event reporting, tags and recurring transactions use real ledger data', async ({ page }) => {
  await page.goto('/#/wallets');
  for (const [name, balance] of [['Ví A', '1000000'], ['Ví B', '0']]) {
    await page.getByRole('button', { name: 'Tạo ví', exact: true }).click(); await page.getByLabel('Tên ví').fill(name); await page.getByLabel('Số dư đầu kỳ').fill(balance); await page.getByRole('button', { name: 'Lưu ví', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  }
  const walletValue = async (label: string, text: string) => { const options = await page.getByLabel(label, { exact: true }).locator('option').allTextContents(); const index = options.findIndex(option => option.endsWith(text)); await page.getByLabel(label, { exact: true }).selectOption({ index }); };
  await page.getByRole('button', { name: 'Tạo giao dịch nhanh' }).click(); await page.getByRole('button', { name: 'Chuyển khoản', exact: true }).click(); await page.getByRole('textbox', { name: 'Số tiền', exact: true }).fill('200000'); await walletValue('Ví gửi', 'Ví A'); await walletValue('Ví nhận', 'Ví B'); await page.getByLabel('Phí chuyển khoản').fill('1000'); await walletValue('Ví trả phí', 'Ví B'); await page.getByRole('button', { name: 'Lưu giao dịch', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.locator('.wallet-card').filter({ hasText: 'Ví A' })).toContainText('800.000'); await expect(page.locator('.wallet-card').filter({ hasText: 'Ví B' })).toContainText('199.000');
  await page.getByRole('button', { name: 'Tạo giao dịch nhanh' }).click(); await page.getByRole('button', { name: 'Cho vay', exact: true }).click(); await page.getByRole('textbox', { name: 'Số tiền', exact: true }).fill('50000'); await walletValue('Ví', 'Ví A'); await page.getByLabel('Người vay', { exact: true }).fill('An kiểm thử'); await page.getByRole('button', { name: 'Lưu giao dịch', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.goto('/#/debts'); await page.getByRole('button', { name: 'Người khác nợ tôi', exact: true }).click(); await page.locator('.debt-card').click(); await page.getByLabel('Số tiền thu').fill('20000'); await walletValue('Ví', 'Ví B'); await page.getByRole('button', { name: 'Ghi nhận thu nợ', exact: true }).click(); await expect(page.locator('.detail-amount')).toContainText('30.000'); await page.getByRole('button', { name: 'Đóng', exact: true }).click();
  await page.goto('/#/events'); await page.getByRole('button', { name: 'Tạo sự kiện', exact: true }).first().click(); await page.getByLabel('Tên sự kiện').fill('Chuyến đi kiểm thử'); await page.getByLabel('Chi dự kiến').fill('100000'); await page.getByRole('button', { name: 'Lưu sự kiện', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Tạo giao dịch nhanh' }).click(); await page.getByRole('button', { name: 'Chi tiêu', exact: true }).click(); await page.getByRole('textbox', { name: 'Số tiền', exact: true }).fill('10000'); await page.getByLabel('Danh mục', { exact: true }).selectOption('expense-0'); await walletValue('Ví', 'Ví A'); await page.getByRole('button', { name: 'Thêm chi tiết' }).click(); await page.getByLabel('Tags', { exact: true }).fill('travel'); await page.getByLabel('Sự kiện', { exact: true }).selectOption({ label: 'Chuyến đi kiểm thử' }); await page.getByRole('button', { name: 'Lưu giao dịch', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.locator('.event-card').click(); await expect(page.locator('.small-metrics')).toContainText('10.000'); await page.getByRole('button', { name: 'Đóng', exact: true }).click();
  await page.goto('/#/tags'); await page.getByRole('button', { name: 'Đổi tên', exact: true }).click(); await page.getByLabel('Tên tag', { exact: true }).fill('holiday'); await page.getByRole('button', { name: 'Lưu tag', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.goto('/#/transactions'); await page.getByRole('textbox', { name: 'Tìm giao dịch' }).fill('holiday'); await expect(page.locator('.transaction-row')).toHaveCount(1);
  await page.goto('/#/recurring'); await page.getByRole('button', { name: 'Tạo lịch', exact: true }).click(); await page.getByLabel('Số tiền', { exact: false }).fill('5000'); await page.getByLabel('Danh mục', { exact: true }).selectOption('expense-0'); await walletValue('Ví', 'Ví A'); await page.getByLabel('Ghi chú', { exact: true }).fill('Lịch kiểm thử'); await page.getByRole('button', { name: 'Lưu lịch', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await page.getByRole('button', { name: 'Kiểm tra hôm nay', exact: true }).click();
  await page.goto('/#/wallets'); await expect(page.locator('.wallet-card').filter({ hasText: 'Ví A' })).toContainText('735.000'); await expect(page.locator('.wallet-card').filter({ hasText: 'Ví B' })).toContainText('219.000');
});

test('generic Excel import previews, blocks invalid rows and deduplicates reimport', async ({ page }) => {
  const date = new Date(); const dateText = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
  const row = { date: dateText, amount: 125000, type: 'income', wallet: 'Ví Excel', category: 'Thu nhập Excel', note: 'Excel sample' };
  const file = (invalid: boolean) => { const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(invalid ? [row, { ...row, amount: '' }] : [row]), 'Ledger'); return { name: 'sample.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: Buffer.from(XLSX.write(book, { type: 'buffer', bookType: 'xlsx' })) }; };
  await page.goto('/#/settings'); await page.getByRole('button', { name: 'Nhập Excel thông thường' }).click();
  const upload = async (invalid: boolean) => { await page.getByLabel('Chọn workbook Excel', { exact: true }).setInputFiles(file(invalid)); for (const [label, value] of [['Ngày *', 'date'], ['Số tiền *', 'amount'], ['Loại *', 'type'], ['Ví *', 'wallet'], ['Danh mục *', 'category'], ['Ghi chú', 'note']]) await page.getByLabel(label, { exact: true }).selectOption(value); await page.getByRole('button', { name: 'Kiểm tra & xem trước', exact: true }).click(); };
  await upload(true); await expect(page.getByRole('button', { name: 'Nhập 1 giao dịch', exact: true })).toBeDisabled(); await expect(page.locator('.import-issues')).toContainText('Dòng 3');
  await upload(false); await page.getByRole('button', { name: 'Nhập 1 giao dịch', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Đã nhập & đối chiếu batch' })).toBeVisible(); await page.getByRole('button', { name: 'Hoàn tất', exact: true }).click();
  await page.getByRole('button', { name: 'Nhập Excel thông thường' }).click(); await upload(false); await expect(page.getByRole('button', { name: 'Nhập 0 giao dịch', exact: true })).toBeDisabled(); await expect(page.locator('.small-metrics')).toContainText('Trùng đã bỏ qua'); await page.getByRole('button', { name: 'Đóng', exact: true }).click();
  await page.goto('/#/wallets'); await expect(page.locator('.wallet-card')).toContainText('125.000');
});
