import { describe, it, expect } from 'vitest';
import * as XLSX from 'xlsx';
import { inspectWorkbook, parseImportDate, parseImportNumber, prepareGenericImport, commitGenericImport, type ImportMapping } from '../src/excel';
import { db } from '../src/db';
import { getBalances } from '../src/services';
const mapping: ImportMapping = { date: 'date', amount: 'amount', type: 'type', wallet: 'wallet', category: 'category', note: 'note', dateFormat: 'dd/MM/yyyy', numberFormat: 'vi-VN', currency: 'VND' };
function workbook(rows: Record<string, unknown>[]) { const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), 'Ledger'); return XLSX.write(book, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer; }
const row = { date: '06/10/2026', amount: '1.250.000', type: 'income', wallet: 'Ngân hàng', category: 'Lương', note: 'A' };
describe('Excel inspection and migration', () => {
  it('inspects sheets, headers, row samples and numeric/string types', () => { const sheets = inspectWorkbook(workbook([row, { ...row, amount: 25000 }])); expect(sheets[0].name).toBe('Ledger'); expect(sheets[0].headers).toContain('amount'); expect(sheets[0].types.amount).toEqual(['string', 'number']); expect(sheets[0].sample).toHaveLength(2); });
  it('parses explicit date and number formats with no ambiguous guesses', () => { expect(parseImportDate('06/10/2026', 'dd/MM/yyyy')).toBe('2026-10-06'); expect(parseImportDate('06/10/2026', 'MM/dd/yyyy')).toBe('2026-06-10'); expect(parseImportDate(46200, 'excel')).toMatch(/^2026-/); expect(parseImportNumber('1.250.000 ₫', 'vi-VN')).toBe(1250000); expect(parseImportNumber('1,250,000', 'en-US')).toBe(1250000); expect(() => parseImportNumber('1,25', 'vi-VN')).toThrow(); expect(() => parseImportDate('30/02/2026', 'dd/MM/yyyy')).toThrow(); });
  it('previews without writing and rejects the entire batch with issues', async () => { const sheets = inspectWorkbook(workbook([row, { ...row, amount: '' }])); const preview = await prepareGenericImport(sheets[0], mapping, 'private.xlsx'); expect(preview.transactions).toHaveLength(1); expect(preview.issues[0].row).toBe(3); expect(await db.wallets.count()).toBe(0); await expect(commitGenericImport(preview)).rejects.toThrow(); expect(await db.transactions.count()).toBe(0); });
  it('imports atomically, reconciles totals and detects the same workbook twice', async () => { const sheets = inspectWorkbook(workbook([row, { ...row, type: 'expense', amount: '250.000', category: 'Ăn uống', note: 'B' }])); const preview = await prepareGenericImport(sheets[0], mapping, 'private.xlsx'); expect(preview.issues).toHaveLength(0); const report = await commitGenericImport(preview); expect(report.count).toBe(2); expect(report.income).toBe(1250000); expect(report.expense).toBe(250000); expect(Object.values(await getBalances())).toContain(1000000); const again = await prepareGenericImport(sheets[0], mapping, 'private-copy.xlsx'); expect(again.duplicates).toBe(2); expect(again.transactions).toHaveLength(0); expect(await db.transactions.count()).toBe(2); });
  it('uses source IDs to preserve financially identical independent entries', async () => { const sheet = inspectWorkbook(workbook([{ ...row, sourceId: '1' }, { ...row, sourceId: '2' }]))[0]; const preview = await prepareGenericImport(sheet, { ...mapping, sourceId: 'sourceId' }, 'source.xlsx'); expect(preview.transactions).toHaveLength(2); await commitGenericImport(preview); const again = await prepareGenericImport(sheet, { ...mapping, sourceId: 'sourceId' }, 'renamed.xlsx'); expect(again.duplicates).toBe(2); });
  it('handles transfers and detects missing destination without discarding a row', async () => { const sheet = inspectWorkbook(workbook([{ ...row, type: 'transfer', destination: 'Tiền mặt', fee: 1000 }]))[0]; const invalid = await prepareGenericImport(sheet, mapping, 'source.xlsx'); expect(invalid.issues).toHaveLength(1); const preview = await prepareGenericImport(sheet, { ...mapping, destination: 'destination', fee: 'fee' }, 'source.xlsx'); await commitGenericImport(preview); const balances = await getBalances(); const bank = (await db.wallets.toArray()).find(w => w.name === 'Ngân hàng')!; const cash = (await db.wallets.toArray()).find(w => w.name === 'Tiền mặt')!; expect(balances[bank.id]).toBe(-1251000); expect(balances[cash.id]).toBe(1250000); });
  it('detects a stale preview when another batch already committed', async () => { const sheet = inspectWorkbook(workbook([row]))[0]; const a = await prepareGenericImport(sheet, mapping, 'a.xlsx'), b = await prepareGenericImport(sheet, mapping, 'b.xlsx'); await commitGenericImport(a); await expect(commitGenericImport(b)).rejects.toThrow('đã thay đổi'); expect(await db.transactions.count()).toBe(1); });
  it('preserves repeated identical rows and deduplicates their repeated export', async () => { const sheet = inspectWorkbook(workbook([row, row]))[0]; const a = await prepareGenericImport(sheet, mapping, 'a.xlsx'); expect(a.transactions).toHaveLength(2); await commitGenericImport(a); const again = await prepareGenericImport(sheet, mapping, 'a-copy.xlsx'); expect(again.duplicates).toBe(2); expect(again.transactions).toHaveLength(0); });
  it('flags currency mismatch and trashed records rather than changing meaning', async () => { const sheet = inspectWorkbook(workbook([{ ...row, currency: 'USD' }, { ...row, deletedAt: '2026-10-06T00:00:00.000Z' }]))[0]; const preview = await prepareGenericImport(sheet, mapping, 'a.xlsx'); expect(preview.issues).toHaveLength(2); expect(preview.transactions).toHaveLength(0); });
});
