import { describe, it, expect } from 'vitest';
import { db, FinanceDB, schemaV2 } from '../src/db';
import Dexie from 'dexie';
import { inspectHeDaFiles, prepareHeDaImport, commitHeDaImport, parseHeDaMoney } from '../src/heda';
import { createBackup, readBackup, restoreBackup, checksum } from '../src/backup';
import { getBalances, trashTransaction, permanentDelete } from '../src/services';

import { makeHeDaFixture as fixture } from './fixtures/heda-fixture';

describe('observed HeDa wallet report adapter', () => {
  it('strictly parses currency syntax instead of guessing separators', () => { expect(parseHeDaMoney('-₫1,234,000')).toBe(-1234000); expect(() => parseHeDaMoney('1.234,00')).toThrow(); });
  it('preserves all original rows, parent/subcategory, fees and actual balances', async () => {
    const parsed = await inspectHeDaFiles(fixture()); const preview = await prepareHeDaImport(parsed); expect(preview.issues).toEqual([]); expect(preview.report.sourceRows).toBe(6); expect(preview.report.transactionCount).toBe(4); expect(preview.report.pairedTransfers).toBe(1); expect(preview.report.feeExpense).toBe(1000); expect(preview.report.netWorth).toBe(1469000);
    expect(await db.transactions.count()).toBe(0); await commitHeDaImport(preview, { fifo: true, externalWallets: false }); expect(await db.hedaSourceRows.count()).toBe(6); expect(await db.transactions.count()).toBe(4);
    const wallet = await db.wallets.filter(w => w.name === 'Ngân hàng thử').first(); expect((await getBalances())[wallet!.id]).toBe(719000);
    const expense = await db.transactions.where('type').equals('expense').first(); const child = await db.categories.get(expense!.categoryId!); expect(child?.name).toBe('Bữa trưa'); expect((await db.categories.get(child!.parentId!))?.name).toBe('Ăn uống thử');
    const transfer = await db.transactions.where('type').equals('transfer').first(); expect(await db.hedaSourceRows.where('transactionIds').equals(transfer!.id).count()).toBe(3);
  });
  it('requires explicit approval of allocation rather than guessing silently', async () => { const preview = await prepareHeDaImport(await inspectHeDaFiles(fixture())); await expect(commitHeDaImport(preview, { fifo: false, externalWallets: false })).rejects.toThrow('xác nhận'); expect(await db.transactions.count()).toBe(0); });
  it('splits a collection across FIFO loans while retaining the single source row', async () => { const preview = await prepareHeDaImport(await inspectHeDaFiles(fixture('split'))); expect(preview.issues).toEqual([]); await commitHeDaImport(preview, { fifo: true, externalWallets: false }); const row = await db.hedaSourceRows.filter(r => r.originalType === 'Thu nợ').first(); expect(row?.transactionIds).toHaveLength(2); expect(await db.debtPayments.count()).toBe(2); expect(preview.report.receivables).toBe(50000); });
  it('keeps unknown wallet balances unverified and outside assets after approval', async () => { const preview = await prepareHeDaImport(await inspectHeDaFiles(fixture('external'))); expect(preview.issues).toEqual([]); expect(preview.externalWallets).toEqual(['Ví ẩn thử']); await expect(commitHeDaImport(preview, { fifo: false, externalWallets: false })).rejects.toThrow('xác nhận'); await commitHeDaImport(preview, { fifo: false, externalWallets: true }); const wallet = await db.wallets.filter(w => w.name === 'Ví ẩn thử').first(); expect(wallet?.balanceVerified).toBe(false); expect(wallet?.includeInNetWorth).toBe(false); expect(wallet?.archived).toBe(true); });
  it('blocks a broken balance chain without dropping any source row into the database', async () => { const preview = await prepareHeDaImport(await inspectHeDaFiles(fixture('broken'))); expect(preview.issues.length).toBeGreaterThan(0); await expect(commitHeDaImport(preview, { fifo: true, externalWallets: false })).rejects.toThrow('lỗi'); expect(await db.transactions.count()).toBe(0); });
  it('does not duplicate repeated imports even when the filename changes', async () => { const files = fixture(); let preview = await prepareHeDaImport(await inspectHeDaFiles(files)); await commitHeDaImport(preview, { fifo: true, externalWallets: false }); preview = await prepareHeDaImport(await inspectHeDaFiles([{ ...files[0], name: 'renamed.xlsx' }])); expect(preview.newRows).toBe(0); expect(preview.duplicateRows).toBe(6); expect(preview.newTransactions).toBe(0); await expect(commitHeDaImport(preview, { fifo: true, externalWallets: false })).rejects.toThrow('đã có'); expect(await db.transactions.count()).toBe(4); });
  it('rolls back all additions if writing source rows fails', async () => { const preview = await prepareHeDaImport(await inspectHeDaFiles(fixture())); const fail = () => { throw new Error('Source write failure'); }; db.hedaSourceRows.hook('creating').subscribe(fail); try { await expect(commitHeDaImport(preview, { fifo: true, externalWallets: false })).rejects.toThrow('Source write failure'); } finally { db.hedaSourceRows.hook('creating').unsubscribe(fail); } expect(await db.wallets.count()).toBe(0); expect(await db.transactions.count()).toBe(0); expect(await db.debts.count()).toBe(0); expect(await db.importBatches.count()).toBe(0); });
  it('backs up and restores the complete source-row mapping and reconciliation', async () => { const preview = await prepareHeDaImport(await inspectHeDaFiles(fixture())); await commitHeDaImport(preview, { fifo: true, externalWallets: false }); const backup = await createBackup(); await restoreBackup(await readBackup(JSON.stringify(backup)), 'replace'); expect(await db.hedaSourceRows.count()).toBe(6); expect((await db.importBatches.toArray())[0].reconciliation).toContain('1469000'); });
  it('retains provenance without broken references after permanent deletion', async () => { const preview = await prepareHeDaImport(await inspectHeDaFiles(fixture())); await commitHeDaImport(preview, { fifo: true, externalWallets: false }); const expense = await db.transactions.where('type').equals('expense').first(); await trashTransaction(expense!.id); await permanentDelete(expense!.id); const raw = await db.hedaSourceRows.filter(r => r.originalType === 'Chi tiêu').first(); expect(raw?.transactionIds).toEqual([]); expect(raw?.purgedTransactionIds).toContain(expense!.id); await createBackup(); });
  it('upgrades a v3 backup by adding the source table without changing old records', async () => { const backup = await createBackup(); const { hedaSourceRows: _rows, ...oldData } = backup.data; const payload = { schemaVersion: 3, appVersion: '1.0.0', exportedAt: backup.exportedAt, data: oldData }; const migrated = await readBackup(JSON.stringify({ ...payload, checksum: await checksum(payload) })); expect(migrated.schemaVersion).toBe(4); expect(migrated.data.hedaSourceRows).toEqual([]); expect(migrated.data.categories).toEqual(backup.data.categories); });
  it('migrates an existing v3 database without recreating wallets or transaction IDs', async () => { const name = `v4-${crypto.randomUUID()}`; const old = new Dexie(name); old.version(3).stores({ ...schemaV2, transactions: `${schemaV2.transactions},[date+time]` }); await old.open(); await old.table('wallets').add({ id: 'existing-wallet', openingBalance: 123456 }); old.close(); const upgraded = new FinanceDB(name); await upgraded.open(); expect((await upgraded.wallets.get('existing-wallet'))?.openingBalance).toBe(123456); expect(await upgraded.hedaSourceRows.count()).toBe(0); upgraded.close(); await Dexie.delete(name); });
});
