import { useLiveQuery } from 'dexie-react-hooks';
import { format, addMonths, parseISO, eachDayOfInterval } from 'date-fns';
import { AreaChart, Area, ResponsiveContainer, Tooltip, XAxis, CartesianGrid, PieChart, Pie, Cell } from 'recharts';
import { ArrowUpRight, ArrowDownLeft, ChevronRight, ShieldCheck, Wallet, Plus, ArrowRight, TrendingUp, CalendarDays } from 'lucide-react';
import { db } from './db';
import { aggregate, getBalances, getDebtOverview, queryTransactions } from './services';
import { monthRange, money } from './finance';
import { useApp, PageTitle, MonthSelector, Money, TransactionRow, EmptyState, Loading } from './ui';

export function Dashboard() {
  const { metadata, month, navigate, openTransaction } = useApp();
  const data = useLiveQuery(async () => {
    const [start, end] = monthRange(month); const previousMonth = format(addMonths(parseISO(`${month}-01`), -1), 'yyyy-MM');
    const [summary, previous, balances, debts, recent, budgets] = await Promise.all([aggregate(start, end), aggregate(...monthRange(previousMonth)), getBalances(), getDebtOverview(), queryTransactions({ start, end }, 0, 5), db.budgets.where('month').equals(month).toArray()]);
    return { summary, previous, balances, debts, recent, budgets };
  }, [month]);
  const dateNow = new Date(); const greeting = dateNow.getHours() < 12 ? 'Chào buổi sáng' : dateNow.getHours() < 18 ? 'Chào buổi chiều' : 'Chào buổi tối';
  if (!data) return <><PageTitle eyebrow="SỔ TÀI CHÍNH CỦA BẠN" title="Tổng quan" /><Loading /></>;
  const totalAssets = metadata.wallets.filter(w => w.includeInNetWorth).reduce((s, w) => s + (data.balances[w.id] ?? 0), 0);
  const cash = metadata.wallets.filter(w => w.type === 'cash' && w.includeInNetWorth).reduce((s, w) => s + (data.balances[w.id] ?? 0), 0);
  const overallBudgets = data.budgets.filter(b => !b.categoryId); const budgetLimit = overallBudgets.reduce((s, b) => s + b.amount, 0);
  const categoryData = Object.entries(data.summary.expenseCategories).sort((a, b) => b[1] - a[1]).map(([key, value]) => { const category = metadata.categories.find(c => c.id === key); return { id: key, name: category?.name ?? 'Phí chuyển khoản', value, color: category?.color ?? '#adb8a1', icon: category?.icon ?? '⇄' }; });
  const dailyData = eachDayOfInterval({ start: parseISO(`${month}-01`), end: parseISO(monthRange(month)[1]) }).map(d => ({ date: format(d, 'dd'), expense: data.summary.daily[format(d, 'yyyy-MM-dd')]?.expense ?? 0 }));
  const delta = data.previous.expense ? (data.summary.expense - data.previous.expense) / data.previous.expense * 100 : undefined;
  const openMonth = (type?: 'expense' | 'income') => navigate('transactions', { start: monthRange(month)[0], end: monthRange(month)[1], reportType: type });
  return <><PageTitle eyebrow={`${greeting.toUpperCase()} · ${format(dateNow, 'dd.MM.yyyy')}`} title="Tiền rõ ràng. Sống nhẹ nhàng." description="Một góc nhỏ để chăm sóc tài chính của bạn." action={<MonthSelector />} />
    <div className="dashboard-top"><section className="asset-card"><div className="asset-orbit" /><div className="asset-label"><span>Tổng tài sản</span><ShieldCheck size={20} /></div><button className="asset-value" onClick={() => navigate('wallets')}><Money value={totalAssets} /><ArrowUpRight size={26} /></button><span className="asset-caption">Số dư hiện tại · {metadata.wallets.filter(w => !w.archived).length} ví đang sử dụng</span><div className="asset-breakdown"><button onClick={() => navigate('wallets')}><span>Tiền mặt</span><Money value={cash} /></button><div /><button onClick={() => navigate('wallets')}><span>Tài khoản & tài sản khác</span><Money value={totalAssets - cash} /></button></div><span className="local-mark"><span />Dữ liệu chỉ nằm trên thiết bị của bạn</span></section>
    <div className="month-cards"><button className="metric-card" onClick={() => openMonth('income')}><span className="metric-icon mint"><ArrowDownLeft size={20} /></span><span className="metric-label">Thu nhập tháng</span><Money value={data.summary.income} /><span className="metric-footer">Tiền vào <ArrowUpRight size={16} /></span></button><button className="metric-card" onClick={() => openMonth('expense')}><span className="metric-icon peach"><ArrowUpRight size={20} /></span><span className="metric-label">Chi tiêu tháng</span><Money value={data.summary.expense} /><span className={`metric-footer ${delta !== undefined && delta > 0 ? 'negative' : ''}`}>{delta === undefined ? 'Chưa có tháng trước để so sánh' : `${delta > 0 ? '↑' : '↓'} ${Math.abs(delta).toFixed(1)}% so với tháng trước`}</span></button><button className="metric-card compact" onClick={() => openMonth()}><span className="metric-label">Chênh lệch thu − chi</span><Money value={data.summary.income - data.summary.expense} className={data.summary.income >= data.summary.expense ? 'positive' : 'negative'} /></button></div></div>
    <div className="dashboard-middle"><section className="panel spending-panel"><div className="panel-heading"><div><h2>Nhịp chi tiêu</h2><p>Những khoản nhỏ tạo nên bức tranh lớn.</p></div><button className="icon-button" aria-label="Xem thống kê" onClick={() => navigate('statistics')}><ArrowUpRight size={20} /></button></div><div className="chart-meta"><Money value={data.summary.expense} /><span>trong tháng {Number(month.slice(5))}</span></div><div className="line-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={dailyData} margin={{ top: 10, right: 14, left: 4, bottom: 0 }}><defs><linearGradient id="expenseGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#609a7c" stopOpacity={0.27} /><stop offset="100%" stopColor="#609a7c" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="4 6" vertical={false} stroke="var(--line)" /><XAxis dataKey="date" axisLine={false} tickLine={false} interval={5} tick={{ fill: '#89918a', fontSize: 12 }} /><Tooltip formatter={v => money(Number(v))} labelFormatter={l => `Ngày ${l}`} contentStyle={{ borderRadius: 14, border: 'none' }} /><Area isAnimationActive={false} name="Chi tiêu" dataKey="expense" type="monotone" stroke="#589579" strokeWidth={2.5} fill="url(#expenseGradient)" /></AreaChart></ResponsiveContainer></div><button className="text-link" onClick={() => navigate('statistics')}>Khám phá thống kê <ArrowRight size={15} /></button></section>
    <section className="panel category-panel"><div className="panel-heading"><div><h2>Tiền đi đâu?</h2><p>Chi tiêu theo danh mục</p></div><span className="soft-badge">Tháng {Number(month.slice(5))}</span></div>{categoryData.length ? <><div className="donut-wrap"><ResponsiveContainer width="100%" height={185}><PieChart><Pie isAnimationActive={false} data={categoryData} dataKey="value" nameKey="name" innerRadius={58} outerRadius={78} paddingAngle={4} stroke="none" onClick={(_v, index) => openCategory(categoryData[index].id)}>{categoryData.map(c => <Cell key={c.id} fill={c.color} />)}</Pie><Tooltip formatter={v => money(Number(v))} /></PieChart></ResponsiveContainer><div className="donut-center"><span>{categoryData.length}</span><small>danh mục</small></div></div><div className="category-legend">{categoryData.slice(0, 3).map(c => <button key={c.id} onClick={() => openCategory(c.id)}><span className="legend-dot" style={{ background: c.color }} /><span>{c.name}</span><strong>{data.summary.expense ? Math.round(c.value / data.summary.expense * 100) : 0}%</strong></button>)}</div></> : <EmptyState title="Chưa có khoản chi" description="Biểu đồ sẽ xuất hiện khi bạn ghi chép." action={() => openTransaction('expense')} actionLabel="Ghi khoản chi" />}</section>
    </div><div className="dashboard-bottom"><section className="panel recent-panel"><div className="panel-heading"><div><h2>Ghi chép gần đây</h2><p>Mỗi giao dịch đều có một câu chuyện.</p></div><button className="text-link" onClick={() => openMonth()}>Xem tất cả <ChevronRight size={16} /></button></div>{data.recent.rows.length ? data.recent.rows.map(tx => <TransactionRow key={tx.id} transaction={tx} />) : <EmptyState action={() => openTransaction('expense')} />}</section><div className="right-stack"><button className="panel budget-summary" onClick={() => navigate('plans')}><div><span className="metric-icon cream"><CalendarDays size={20} /></span><ArrowUpRight size={18} /></div><h3>Ngân sách còn lại</h3>{budgetLimit ? <><Money value={budgetLimit - data.summary.expense} className="budget-remaining" /><div className="progress"><span style={{ width: `${Math.min(100, data.summary.expense / budgetLimit * 100)}%`, background: data.summary.expense > budgetLimit ? '#c06a5a' : undefined }} /></div><small>Đã dùng {Math.round(data.summary.expense / budgetLimit * 100)}% của <Money value={budgetLimit} /></small></> : <><p>Lên kế hoạch cho tháng này</p><span className="text-link">Đặt ngân sách <Plus size={15} /></span></>}</button><section className="panel debt-summary"><h3>Vay & cho vay</h3><button onClick={() => navigate('debts')}><span>Người khác nợ bạn</span><Money value={data.debts.filter(d => d.kind === 'lend').reduce((s, d) => s + d.remaining, 0)} /></button><button onClick={() => navigate('debts')}><span>Bạn đang nợ</span><Money value={data.debts.filter(d => d.kind === 'borrow').reduce((s, d) => s + d.remaining, 0)} /></button></section></div></div>
    {!metadata.settings.lastBackup && <button className="backup-nudge" onClick={() => navigate('settings')}><ShieldCheck size={20} /><span><strong>Giữ sổ tài chính luôn an toàn</strong><small>Tải bản sao lưu đầu tiên trong Cài đặt.</small></span><ArrowRight size={18} /></button>}
  </>;
  function openCategory(categoryId: string) { navigate('transactions', { ...Object.fromEntries([['start', monthRange(month)[0]], ['end', monthRange(month)[1]]]), ...(categoryId === 'transfer-fees' ? { type: 'transfer' } : { type: 'expense', reportType: 'expense', categoryId }) }); }
}
