import { useState } from 'react';
export { Debts } from './Debts';
import { useLiveQuery } from 'dexie-react-hooks';
import { Plus, ArrowUpRight, CalendarDays, Repeat, Archive, Tags as TagsIcon, Trash2 } from 'lucide-react';
import { db } from './db';
import { aggregate, generateRecurring, queryTransactions } from './services';
import { today, id, calculateExpression, assertMoney, assertDate } from './finance';
import type { FinanceEvent, RecurringTransaction, Tag } from './types';
import { useApp, PageTitle, Money, Modal, Field, SubmitButton, WalletSelect, CategorySelect, useSubmit, EmptyState, Confirm, TransactionRow } from './ui';

export function Events() {
  const { metadata } = useApp(); const [edit, setEdit] = useState<FinanceEvent | 'new'>(); const [selected, setSelected] = useState<FinanceEvent>();
  return <><PageTitle eyebrow="NHỮNG CỘT MỐC CỦA BẠN" title="Sự kiện" description="Một chuyến đi, một dịp đặc biệt, một kế hoạch riêng." action={<button className="button primary" onClick={() => setEdit('new')}><Plus size={18} />Tạo sự kiện</button>} />{metadata.events.length ? <div className="event-grid">{metadata.events.map(e => <button className="panel event-card" key={e.id} onClick={() => setSelected(e)}><div className="event-decoration"><CalendarDays size={32} /><ArrowUpRight size={20} /></div><h2>{e.name}</h2><p>{e.startDate} → {e.endDate}</p><small>Chi dự kiến <Money value={e.expectedExpense} /></small></button>)}</div> : <section className="panel"><EmptyState title="Dành một góc cho những dịp đặc biệt" description="Liên kết giao dịch với sự kiện để biết tổng thu, chi và phần còn lại." actionLabel="Tạo sự kiện" action={() => setEdit('new')} /></section>}{edit && <EventForm event={edit === 'new' ? undefined : edit} onClose={() => setEdit(undefined)} />}{selected && <EventDetail event={selected} onClose={() => setSelected(undefined)} onEdit={() => { setEdit(selected); setSelected(undefined); }} />}</>;
}
function EventDetail({ event, onClose, onEdit }: { event: FinanceEvent; onClose: () => void; onEdit: () => void }) {
  const { metadata, navigate, run } = useApp(); const [remove, setRemove] = useState(false);
  const summary = useLiveQuery(() => aggregate('0000-01-01', '9999-12-31', { eventId: event.id }), [event.id]);
  const recent = useLiveQuery(() => queryTransactions({ eventId: event.id }, 0, 5), [event.id]);
  const deleteEvent = async () => { await db.transaction('rw', db.events, db.transactions, async () => { await db.transactions.where('eventId').equals(event.id).modify({ eventId: undefined }); await db.events.delete(event.id); }); onClose(); };
  return <><Modal title={event.name} onClose={onClose}><p className="muted">{event.startDate} → {event.endDate}</p><div className="small-metrics"><div><small>Thu nhập</small><Money value={summary?.income ?? 0} /></div><div><small>Chi tiêu</small><Money value={summary?.expense ?? 0} /></div><div><small>Chênh lệch</small><Money value={(summary?.income ?? 0) - (summary?.expense ?? 0)} /></div></div><p className="body-copy">{event.note}</p><p className="muted">Dự kiến: thu <Money value={event.expectedIncome} /> · chi <Money value={event.expectedExpense} /></p><h3 className="section-subtitle">Chi tiêu theo danh mục</h3>{Object.entries(summary?.expenseCategories ?? {}).map(([categoryId, value]) => <div className="simple-row" key={categoryId}><span>{metadata.categories.find(c => c.id === categoryId)?.name ?? 'Phí chuyển khoản'}</span><Money value={value} /></div>)}<h3 className="section-subtitle">Giao dịch gần đây</h3>{recent?.rows.map(tx => <TransactionRow key={tx.id} transaction={tx} />)}<div className="action-list"><button onClick={() => { navigate('transactions', { eventId: event.id }); onClose(); }}>Xem toàn bộ {summary?.count ?? 0} giao dịch <ArrowUpRight size={18} /></button><button onClick={onEdit}>Chỉnh sửa sự kiện</button><button className="danger-text" onClick={() => setRemove(true)}>Xóa sự kiện</button></div></Modal>{remove && <Confirm title="Xóa sự kiện?" message="Giao dịch được giữ nguyên và bỏ liên kết với sự kiện." action={deleteEvent} onClose={() => setRemove(false)} />}</>;
}
function EventForm({ event, onClose }: { event?: FinanceEvent; onClose: () => void }) {
  const [name, setName] = useState(event?.name ?? ''); const [startDate, setStart] = useState(event?.startDate ?? today()); const [endDate, setEnd] = useState(event?.endDate ?? today()); const [expense, setExpense] = useState(String(event?.expectedExpense ?? 0)); const [income, setIncome] = useState(String(event?.expectedIncome ?? 0)); const [note, setNote] = useState(event?.note ?? '');
  const { submit, busy } = useSubmit(async () => { if (!name.trim()) throw new Error('Nhập tên sự kiện.'); assertDate(startDate); assertDate(endDate); if (endDate < startDate) throw new Error('Ngày kết thúc phải sau ngày bắt đầu.'); const expectedExpense = calculateExpression(expense), expectedIncome = calculateExpression(income); if (expectedExpense < 0 || expectedIncome < 0) throw new Error('Số tiền dự kiến không thể âm.'); await db.events.put({ id: event?.id ?? id(), name: name.trim(), startDate, endDate, expectedExpense, expectedIncome, note }); }, 'Đã lưu sự kiện', onClose);
  return <Modal title={event ? 'Sửa sự kiện' : 'Sự kiện mới'} onClose={onClose}><form onSubmit={submit}><Field label="Tên sự kiện"><input value={name} onChange={e => setName(e.target.value)} required autoFocus placeholder="Đà Lạt 2026" /></Field><div className="form-grid"><Field label="Từ ngày"><input type="date" value={startDate} onChange={e => setStart(e.target.value)} required /></Field><Field label="Đến ngày"><input type="date" value={endDate} onChange={e => setEnd(e.target.value)} required /></Field><Field label="Chi dự kiến · VND"><input inputMode="numeric" value={expense} onChange={e => setExpense(e.target.value)} required /></Field><Field label="Thu dự kiến · VND"><input inputMode="numeric" value={income} onChange={e => setIncome(e.target.value)} required /></Field></div><Field label="Ghi chú"><textarea value={note} onChange={e => setNote(e.target.value)} /></Field><SubmitButton busy={busy} label="Lưu sự kiện" /></form></Modal>;
}
export function Recurring() {
  const { metadata, run } = useApp(); const rules = useLiveQuery(() => db.recurring.toArray(), [], []); const [edit, setEdit] = useState<RecurringTransaction | 'new'>();
  const frequencies = { daily: 'Hàng ngày', weekly: 'Hàng tuần', monthly: 'Hàng tháng', yearly: 'Hàng năm', custom: 'Theo khoảng ngày' };
  return <><PageTitle eyebrow="GIỮ NHỊP, KHÔNG QUÊN" title="Giao dịch định kỳ" description="App kiểm tra những lần còn thiếu khi mở; mỗi kỳ chỉ được tạo một lần." action={<button className="button primary" onClick={() => setEdit('new')}><Plus size={18} />Tạo lịch</button>} />{rules.length ? <div className="recurring-grid">{rules.map(r => <section className={`panel recurring-card ${r.archived ? 'archived' : ''}`} key={r.id}><button className="budget-card-title" onClick={() => setEdit(r)}><span className="category-icon"><Repeat size={22} /></span><span><h2>{r.note || metadata.categories.find(c => c.id === r.categoryId)?.name}</h2><small>{frequencies[r.frequency]}{r.frequency === 'custom' && ` · ${r.interval} ngày`} · {r.archived ? 'Đã dừng' : r.autoCreate ? 'Tự động khi mở app' : 'Xác nhận thủ công'}</small></span></button><Money value={r.amount} /><p className="muted">{r.type === 'income' ? 'Thu nhập' : 'Chi tiêu'} · {metadata.wallets.find(w => w.id === r.walletId)?.name}</p><small>Kỳ tiếp theo: {r.nextRunDate}{r.endDate && ` · Kết thúc: ${r.endDate}`}</small><div className="form-actions"><button className="button secondary" disabled={r.archived} onClick={() => void run(() => generateRecurring(today(), r.id, true), 'Đã kiểm tra và tạo các kỳ còn thiếu')}>Kiểm tra hôm nay</button><button className="icon-button" aria-label={r.archived ? 'Mở lại lịch' : 'Dừng lịch'} onClick={() => void run(() => db.recurring.update(r.id, { archived: !r.archived }), r.archived ? 'Đã mở lại lịch' : 'Đã dừng lịch')}><Archive size={18} /></button></div></section>)}</div> : <section className="panel"><EmptyState icon={<Repeat size={30} />} title="Cho những khoản đều đặn" description="Tiền thuê nhà, lương hàng tháng hoặc khoản chi hàng tuần." actionLabel="Tạo lịch định kỳ" action={() => setEdit('new')} /></section>}{edit && <RecurringForm rule={edit === 'new' ? undefined : edit} onClose={() => setEdit(undefined)} />}</>;
}
function RecurringForm({ rule, onClose }: { rule?: RecurringTransaction; onClose: () => void }) {
  const { metadata } = useApp(); const [type, setType] = useState<'income' | 'expense'>(rule?.type ?? 'expense'); const [amount, setAmount] = useState(rule ? String(rule.amount) : ''); const [categoryId, setCategory] = useState(rule?.categoryId ?? ''); const [walletId, setWallet] = useState(rule?.walletId ?? metadata.settings.defaultWalletId ?? ''); const [frequency, setFrequency] = useState(rule?.frequency ?? 'monthly'); const [interval, setInterval] = useState(String(rule?.interval ?? 1)); const [startDate, setStart] = useState(rule?.startDate ?? today()); const [endDate, setEnd] = useState(rule?.endDate ?? ''); const [note, setNote] = useState(rule?.note ?? ''); const [auto, setAuto] = useState(rule?.autoCreate ?? true);
  const { submit, busy } = useSubmit(async () => {
    const value = calculateExpression(amount); assertMoney(value); assertDate(startDate); if (endDate) { assertDate(endDate); if (endDate < startDate) throw new Error('Ngày kết thúc phải sau ngày bắt đầu.'); }
    const customInterval = Number(interval); if (!Number.isSafeInteger(customInterval) || customInterval < 1 || customInterval > 36500) throw new Error('Khoảng ngày không hợp lệ.');
    if (!metadata.wallets.some(w => w.id === walletId && !w.archived) || !metadata.categories.some(c => c.id === categoryId && c.type === type && !c.archived)) throw new Error('Chọn ví và danh mục đang hoạt động.');
    const ruleId = rule?.id ?? id();
    await db.transaction('rw', [db.recurring, db.transactions, db.wallets, db.categories, db.events], async () => {
      await db.recurring.put({ id: ruleId, type, amount: value, categoryId, walletId, note, frequency, interval: customInterval, startDate, endDate: endDate || undefined, nextRunDate: rule?.nextRunDate ?? startDate, autoCreate: auto, archived: rule?.archived ?? false, anchorDay: Number(startDate.slice(-2)) });
      if (auto) await generateRecurring(today(), ruleId);
    });
  }, 'Đã lưu lịch định kỳ', onClose);
  return <Modal title={rule ? 'Sửa lịch định kỳ' : 'Lịch định kỳ mới'} onClose={onClose}><form onSubmit={submit}><Field label="Loại"><select value={type} onChange={e => { setType(e.target.value as 'income' | 'expense'); setCategory(''); }}><option value="expense">Chi tiêu</option><option value="income">Thu nhập</option></select></Field><Field label="Số tiền · VND"><input inputMode="numeric" value={amount} onChange={e => setAmount(e.target.value)} required /></Field><div className="form-grid"><Field label="Danh mục"><CategorySelect type={type} value={categoryId} onChange={setCategory} /></Field><Field label="Ví"><WalletSelect value={walletId} onChange={setWallet} /></Field></div><Field label="Tần suất"><select value={frequency} disabled={!!rule} onChange={e => setFrequency(e.target.value as RecurringTransaction['frequency'])}><option value="daily">Hàng ngày</option><option value="weekly">Hàng tuần</option><option value="monthly">Hàng tháng</option><option value="yearly">Hàng năm</option><option value="custom">Khoảng ngày tùy chọn</option></select></Field>{frequency === 'custom' && <Field label="Lặp mỗi số ngày"><input type="number" min={1} max={36500} value={interval} disabled={!!rule} onChange={e => setInterval(e.target.value)} required /></Field>}<div className="form-grid"><Field label="Ngày bắt đầu"><input type="date" disabled={!!rule} value={startDate} onChange={e => setStart(e.target.value)} required /></Field><Field label="Ngày kết thúc (tùy chọn)"><input type="date" value={endDate} onChange={e => setEnd(e.target.value)} /></Field></div><Field label="Ghi chú"><input value={note} onChange={e => setNote(e.target.value)} /></Field><label className="check-field"><input type="checkbox" checked={auto} onChange={e => setAuto(e.target.checked)} />Tự tạo các kỳ còn thiếu khi mở app</label><p className="footnote">Ngày bắt đầu và tần suất cố định sau khi tạo để bảo toàn lịch sử. Có thể dừng lịch cũ và tạo lịch mới.</p><SubmitButton busy={busy} label="Lưu lịch" /></form></Modal>;
}
export function Tags() {
  const { metadata, navigate } = useApp(); const [edit, setEdit] = useState<Tag | 'new'>(); const [remove, setRemove] = useState<Tag>();
  const deleteTag = async (tag: Tag) => db.transaction('rw', db.tags, db.transactionTags, db.transactions, async () => { await db.transactions.where('tags').equals(tag.name).modify(t => { t.tags = t.tags.filter(name => name !== tag.name); }); await db.transactionTags.where('tagId').equals(tag.id).delete(); await db.tags.delete(tag.id); });
  return <><PageTitle eyebrow="KẾT NỐI CÁC GHI CHÉP" title="Tags" description="Một giao dịch có thể thuộc nhiều chủ đề." action={<button className="button primary" onClick={() => setEdit('new')}><Plus size={18} />Thêm tag</button>} /><section className="panel">{metadata.tags.length ? metadata.tags.map(t => <div className="simple-row" key={t.id}><button className="text-link" onClick={() => navigate('transactions', { tag: t.name })}><TagsIcon size={18} />#{t.name}</button><div><button className="button ghost" onClick={() => setEdit(t)}>Đổi tên</button><button className="icon-button" aria-label={`Xóa tag ${t.name}`} onClick={() => setRemove(t)}><Trash2 size={17} /></button></div></div>) : <EmptyState title="Gắn nhãn theo cách của bạn" description="#work, #travel, #family… tạo tag ở đây hoặc khi ghi giao dịch." actionLabel="Thêm tag" action={() => setEdit('new')} />}</section>{edit && <TagForm tag={edit === 'new' ? undefined : edit} onClose={() => setEdit(undefined)} />}{remove && <Confirm title="Xóa tag?" message="Giao dịch vẫn được giữ lại, chỉ bỏ nhãn này." action={() => deleteTag(remove)} onClose={() => setRemove(undefined)} />}</>;
}
function TagForm({ tag, onClose }: { tag?: Tag; onClose: () => void }) {
  const [name, setName] = useState(tag?.name ?? '');
  const { submit, busy } = useSubmit(async () => {
    const value = name.trim().replace(/^#/, ''); if (!value || value.length > 200 || /[,#]/.test(value)) throw new Error('Tên tag không hợp lệ.');
    await db.transaction('rw', db.tags, db.transactions, async () => {
      const existing = await db.tags.where('name').equals(value).first(); if (existing && existing.id !== tag?.id) throw new Error('Tag đã tồn tại.');
      if (tag) await db.transactions.where('tags').equals(tag.name).modify(t => { t.tags = [...new Set(t.tags.map(n => n === tag.name ? value : n))]; });
      await db.tags.put({ id: tag?.id ?? id(), name: value });
    });
  }, 'Đã lưu tag', onClose);
  return <Modal title={tag ? 'Đổi tên tag' : 'Tag mới'} onClose={onClose}><form onSubmit={submit}><Field label="Tên tag"><input required value={name} onChange={e => setName(e.target.value)} placeholder="travel" autoFocus /></Field><SubmitButton busy={busy} label="Lưu tag" /></form></Modal>;
}
