import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Download, Upload, ShieldCheck, ChevronRight, Wallet, Tags, Shapes, Repeat, CalendarDays, Trash2, Settings as SettingsIcon, BookOpen, MonitorSmartphone, Database, FileSpreadsheet, AlertCircle } from 'lucide-react';
import { formatDistanceToNow, parseISO, differenceInDays } from 'date-fns';
import { vi } from 'date-fns/locale';
import { db } from './db';
import { HeDaImport, HeDaHistory } from './HeDaImport';
import { APP_VERSION, DB_VERSION, type AppSettings } from './types';
import { exportBackup, readBackup, restoreBackup, resetAllData, downloadFile, type Backup } from './backup';
import { exportExcel, inspectWorkbook, prepareGenericImport, commitGenericImport, type InspectedSheet, type ImportMapping, type ImportPreview } from './excel';
import { emptyTrash, permanentDelete, restoreTransaction, seedDemo, getBalances } from './services';
import { useApp, PageTitle, Modal, Field, Confirm, EmptyState, Money } from './ui';

export function More() {
  const { navigate } = useApp();
  const links = [ ['wallets', 'Ví & tài sản', 'Số dư, chuyển tiền, điều chỉnh', Wallet], ['categories', 'Danh mục', 'Thu nhập, chi tiêu và danh mục con', Shapes], ['debts', 'Vay & cho vay', 'Gốc, dư nợ và lịch sử thanh toán', BookOpen], ['events', 'Sự kiện', 'Dành riêng cho những dịp đặc biệt', CalendarDays], ['recurring', 'Giao dịch định kỳ', 'Ghi chép tự động khi mở app', Repeat], ['tags', 'Tags', 'Kết nối giao dịch theo chủ đề', Tags], ['trash', 'Thùng rác', 'Khôi phục ghi chép đã xóa', Trash2], ['settings', 'Cài đặt & dữ liệu', 'Backup, Excel và giao diện', SettingsIcon] ] as const;
  return <><PageTitle eyebrow="MỘT GÓC CHO MỌI THỨ" title="Sổ của bạn" description="Riêng tư. Không tài khoản. Không phí sử dụng." /><section className="panel more-list">{links.map(([route, title, description, Icon]) => <button key={route} onClick={() => navigate(route)}><span className="more-icon"><Icon size={23} /></span><span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={20} /></button>)}</section></>;
}
export function Trash() {
  const { run } = useApp(); const rows = useLiveQuery(() => db.transactions.filter(t => !!t.deletedAt).limit(41).toArray(), [], []); const count = useLiveQuery(() => db.transactions.filter(t => !!t.deletedAt).count(), [], 0); const [remove, setRemove] = useState<string>(); const [empty, setEmpty] = useState(false);
  return <><PageTitle eyebrow="CÓ THỂ BẮT ĐẦU LẠI" title="Thùng rác" description={`${count} giao dịch. Các bản ghi này không tính vào số dư hoặc báo cáo.`} action={count > 0 && <button className="button danger" onClick={() => setEmpty(true)}>Dọn thùng rác</button>} /><section className="panel">{rows.length ? rows.slice(0, 40).map(tx => <div className="trash-row" key={tx.id}><div><strong>{tx.note || tx.type}</strong><small>Xóa: {tx.deletedAt?.slice(0, 10)} · Giao dịch: {tx.date}</small><Money value={tx.amount} /></div><div><button className="button secondary" onClick={() => void run(() => restoreTransaction(tx.id), 'Đã khôi phục giao dịch')}>Khôi phục</button><button className="icon-button danger-text" aria-label="Xóa vĩnh viễn" onClick={() => setRemove(tx.id)}><Trash2 size={18} /></button></div></div>) : <EmptyState title="Thùng rác đang trống" description="Giao dịch bị xóa sẽ ở đây để bạn có thể khôi phục." />}{count > 40 && <p className="notice">Đang hiện 40 bản ghi đầu tiên. Khôi phục hoặc xóa để xem các bản ghi tiếp theo.</p>}</section>{remove && <Confirm title="Xóa vĩnh viễn?" message="Không thể khôi phục giao dịch này sau khi xóa. Nếu được nhập từ HeDa, dòng nguồn vẫn được giữ làm tài liệu đối chiếu trong backup." action={() => permanentDelete(remove)} onClose={() => setRemove(undefined)} />}{empty && <Confirm title="Dọn sạch thùng rác?" message="Toàn bộ giao dịch đã xóa sẽ bị xóa vĩnh viễn. Các bút toán nợ liên quan được xử lý cùng nhau." action={emptyTrash} onClose={() => setEmpty(false)} />}</>;
}
export function Settings() {
  const { metadata, run, notify } = useApp(); const [backup, setBackup] = useState<Backup>(); const [replace, setReplace] = useState(false); const [reset, setReset] = useState(false); const [excelMode, setExcelMode] = useState<'generic' | 'heda'>(); const [install, setInstall] = useState(false); const [hedaHistory, setHeDaHistory] = useState(false); const [busy, setBusy] = useState(false);
  const count = useLiveQuery(() => db.transactions.count(), [], 0); const [storage, setStorage] = useState(''); const [exportedBackup, setExportedBackup] = useState<Backup>(); const [showBackupJson, setShowBackupJson] = useState(false);
  const settings = metadata.settings;
  const update = (patch: Partial<AppSettings>) => void run(() => db.settings.update('app', patch), 'Đã lưu cài đặt');
  const withBusy = async (action: () => Promise<unknown>, success: string) => { if (busy) return; setBusy(true); try { await run(action, success); } finally { setBusy(false); } };
  const prepareBackupFile = async () => { const result = await exportBackup(); setExportedBackup(result); setShowBackupJson(false); };
  const loadBackup = async (file?: File) => { if (!file) return; await withBusy(async () => { if (file.size > 150000000) throw new Error('File quá lớn (giới hạn 150 MB).'); setBackup(await readBackup(await file.text())); }, 'Backup hợp lệ. Kiểm tra trước khi khôi phục.'); };
  const lastBackup = settings.lastBackup ? formatDistanceToNow(parseISO(settings.lastBackup), { locale: vi, addSuffix: true }) : 'Chưa có bản sao lưu';
  const late = !settings.lastBackup || differenceInDays(new Date(), parseISO(settings.lastBackup)) >= 7;
  return <><PageTitle eyebrow="DỮ LIỆU THUỘC VỀ BẠN" title="Cài đặt" description="Một ứng dụng nhỏ. Một sổ tài chính dài lâu." />
    <section className={`backup-banner ${late ? 'backup-due' : ''}`}><span className="backup-icon"><ShieldCheck size={28} /></span><div><h2>{late ? 'Dành một phút để sao lưu' : 'An tâm với bản sao lưu'}</h2><p>Lần backup gần nhất: {lastBackup}</p><small>Lưu file ở nơi an toàn. Dữ liệu trình duyệt có thể bị xóa khi đổi hoặc reset thiết bị.</small></div><button className="button primary" disabled={busy} onClick={() => void withBusy(prepareBackupFile, 'Đã tạo file backup. Kiểm tra file trong thư mục tải xuống.')}><Download size={18} />Tải backup</button></section>
    <div className="settings-grid"><section className="panel"><div className="panel-heading"><h2>Chung</h2><SettingsIcon size={19} /></div><Field label="Tiền tệ"><select value={settings.currency} onChange={e => update({ currency: e.target.value })}><option value="VND">VND · Đồng Việt Nam</option></select></Field><Field label="Giao diện"><select value={settings.theme} onChange={e => update({ theme: e.target.value as AppSettings['theme'] })}><option value="system">Theo thiết bị</option><option value="light">Sáng</option><option value="dark">Tối</option></select></Field><Field label="Ngày đầu tuần"><select value={settings.firstDayOfWeek} onChange={e => update({ firstDayOfWeek: Number(e.target.value) as 0 | 1 })}><option value={1}>Thứ hai</option><option value={0}>Chủ nhật</option></select></Field><Field label="Định dạng ngày"><select value={settings.dateFormat} onChange={e => update({ dateFormat: e.target.value as AppSettings['dateFormat'] })}><option value="dd/MM/yyyy">06/10/2026</option><option value="yyyy-MM-dd">2026-10-06</option></select></Field><Field label="Định dạng số"><select value={settings.numberFormat} onChange={e => update({ numberFormat: e.target.value as AppSettings['numberFormat'] })}><option value="vi-VN">1.250.000 ₫</option><option value="en-US">₫1,250,000</option></select></Field></section>
    <section className="panel"><div className="panel-heading"><h2>Dữ liệu</h2><Database size={20} /></div><div className="settings-actions"><button disabled={busy} onClick={() => void withBusy(prepareBackupFile, 'Đã tạo file backup')}><Download size={19} /><span>Xuất backup JSON<small>Toàn bộ dữ liệu, kèm checksum SHA-256</small></span><ChevronRight size={18} /></button><label className="file-action"><Upload size={19} /><span>Khôi phục backup<small>Xác thực → xem trước → gộp hoặc thay thế</small></span><input type="file" accept=".json,application/json" disabled={busy} aria-label="Chọn file backup" onChange={e => { void loadBackup(e.target.files?.[0]); e.target.value = ''; }} /><ChevronRight size={18} /></label><button disabled={busy} onClick={() => void withBusy(exportExcel, 'Đã tạo file Excel')}><FileSpreadsheet size={19} /><span>Xuất Excel<small>Giao dịch, ví, ngân sách và toàn bộ bảng dữ liệu</small></span><ChevronRight size={18} /></button><button onClick={() => setExcelMode('generic')}><Upload size={19} /><span>Nhập Excel thông thường<small>Tự chọn cột, kiểm tra lỗi và chống trùng</small></span><ChevronRight size={18} /></button><button onClick={() => setExcelMode('heda')}><FileSpreadsheet size={19} /><span>Nhập Excel HeDa<small>Ghép chuyển khoản, liên kết nợ và đối chiếu nguồn</small></span><ChevronRight size={18} /></button><button onClick={() => setHeDaHistory(true)}><FileSpreadsheet size={19} /><span>Báo cáo nhập HeDa<small>Đối chiếu và các ngoại lệ nguồn được giữ lại</small></span><ChevronRight size={18} /></button><button onClick={() => setInstall(true)}><MonitorSmartphone size={19} /><span>Cài app trên iPhone<small>Add to Home Screen từ Safari</small></span><ChevronRight size={18} /></button></div></section>
    <section className="panel"><div className="panel-heading"><h2>Về Mộc</h2><ShieldCheck size={19} /></div><div className="simple-row"><span>Phiên bản ứng dụng</span><strong>{APP_VERSION}</strong></div><div className="simple-row"><span>Phiên bản database</span><strong>{DB_VERSION}</strong></div><div className="simple-row"><span>Tổng số giao dịch</span><strong>{count.toLocaleString('vi-VN')}</strong></div><div className="simple-row"><span>Dung lượng lưu trữ</span><button className="text-link" onClick={() => void run(async () => { const estimate = await navigator.storage?.estimate?.(); setStorage(estimate?.usage !== undefined ? `${(estimate.usage / 1024 / 1024).toFixed(2)} MB (toàn origin)` : 'Trình duyệt không cung cấp'); })}>{storage || 'Kiểm tra'}</button></div><p className="notice"><ShieldCheck size={18} />Không tài khoản, không analytics. Dữ liệu nằm trong IndexedDB của thiết bị này.</p><button className="button secondary" onClick={() => void run(async () => { const result = await navigator.storage?.persist?.(); notify(result ? 'Trình duyệt đã cấp lưu trữ bền vững' : 'Trình duyệt chưa cấp lưu trữ bền vững. Tiếp tục sao lưu thường xuyên.'); })}>Yêu cầu lưu trữ bền vững</button></section>
    <section className="panel"><h2>Đặt lại dữ liệu</h2><p className="body-copy">Xóa toàn bộ ví, giao dịch và cài đặt trên thiết bị này. Hãy tải và giữ một bản backup trước khi thực hiện.</p><button className="button danger" onClick={() => setReset(true)}><Trash2 size={17} />Xóa toàn bộ dữ liệu</button></section></div>
    {import.meta.env.DEV && <section className="panel dev-tools"><h2>Development tools</h2><p className="footnote">Chỉ hiển thị trong development. Dữ liệu mẫu chỉ được thêm vào database chưa có ví / giao dịch.</p><div className="form-actions">{[90, 1000, 10000, 100000].map(size => <button className="button secondary" key={size} disabled={busy} onClick={() => void withBusy(() => seedDemo(size), `Đã thêm ${size} giao dịch mẫu`)}>Seed {size.toLocaleString()}</button>)}<button className="button secondary" onClick={() => void run(async () => { const balances = await getBalances(); notify(`Đã tính lại ${Object.keys(balances).length} số dư từ lịch sử.`); })}>Kiểm tra số dư</button></div></section>}
    {exportedBackup && <Modal title="Bản sao lưu đã tạo" onClose={() => setExportedBackup(undefined)}><p className="notice"><ShieldCheck size={18} />Backup đã kiểm tra dữ liệu và có checksum SHA-256.</p><p className="body-copy">{exportedBackup.data.transactions.length.toLocaleString('vi-VN')} giao dịch · {exportedBackup.data.hedaSourceRows.length.toLocaleString('vi-VN')} dòng nguồn HeDa · {Object.keys(exportedBackup.data).length} bảng.</p><p className="footnote">Nếu trình duyệt chưa lưu file, tải lại hoặc sao chép JSON bên dưới thành file .json. Không đóng cửa sổ trước khi đã giữ một bản sao.</p><button className="button primary submit-button" onClick={() => downloadFile(JSON.stringify(exportedBackup, null, 2), `personal-finance-backup-${exportedBackup.exportedAt.slice(0, 10)}.json`)}>Tải lại file backup</button><button className="text-link" onClick={() => setShowBackupJson(value => !value)}>{showBackupJson ? 'Ẩn nội dung JSON' : 'Hiện JSON để sao chép'}</button>{showBackupJson && <Field label="Nội dung backup JSON"><textarea readOnly rows={8} spellCheck={false} value={JSON.stringify(exportedBackup, null, 2)} className="backup-json" /></Field>}<button className="button secondary submit-button" onClick={() => setExportedBackup(undefined)}>Hoàn tất lưu backup</button></Modal>}
    {backup && <Modal title="Xem trước khôi phục" onClose={() => setBackup(undefined)}><p className="notice"><ShieldCheck size={18} />Checksum và các liên kết dữ liệu hợp lệ.</p><p className="muted">Xuất ngày {backup.exportedAt} · App {backup.appVersion}</p><div className="restore-counts">{Object.entries(backup.data).map(([name, rows]) => <div className="simple-row" key={name}><span>{name}</span><strong>{rows.length.toLocaleString('vi-VN')}</strong></div>)}</div><p className="body-copy">Gộp chỉ nhận bản ghi mới và bản ghi trùng khớp. ID xung đột sẽ dừng toàn bộ quá trình. Thay thế sử dụng toàn bộ bản backup.</p><div className="form-actions"><button className="button secondary" disabled={busy} onClick={async () => { setBusy(true); try { if (await run(() => restoreBackup(backup, 'merge'), 'Đã gộp backup')) setBackup(undefined); } finally { setBusy(false); } }}>Gộp dữ liệu</button><button className="button danger" onClick={() => setReplace(true)}>Thay thế dữ liệu</button></div></Modal>}
    {replace && backup && <Confirm title="Thay thế bằng backup?" message="Toàn bộ dữ liệu hiện tại sẽ được thay bằng bản backup đã kiểm tra. Thao tác ghi là atomic và rollback nếu thất bại. Bạn nên giữ backup của dữ liệu hiện tại trước." action={async () => { await restoreBackup(backup, 'replace'); setBackup(undefined); }} onClose={() => setReplace(false)} />}
    {reset && <Confirm title="Xóa toàn bộ dữ liệu?" message="Không thể khôi phục nếu không có backup. Hãy tải backup trước khi xác nhận." strong action={() => resetAllData('XÓA TẤT CẢ')} onClose={() => setReset(false)} />}
    {excelMode === 'heda' && <HeDaImport onClose={() => setExcelMode(undefined)} />}{excelMode === 'generic' && <ExcelImport mode="generic" onClose={() => setExcelMode(undefined)} />}{hedaHistory && <HeDaHistory onClose={() => setHeDaHistory(false)} />}
    {install && <Modal title="Mang Mộc lên màn hình chính" onClose={() => setInstall(false)}><ol className="install-steps"><li>Mở URL đã deploy bằng Safari trên iPhone / iPad.</li><li>Bấm nút Chia sẻ, chọn <strong>Thêm vào Màn hình chính</strong>.</li><li>Giữ tên Mộc rồi bấm <strong>Thêm</strong>.</li><li>Mở Mộc từ màn hình chính. Sau lần tải đầu tiên, app có thể hoạt động offline.</li></ol><p className="notice">Mỗi thiết bị và mỗi trình duyệt có database riêng. Dùng backup / restore để chuyển sổ sang thiết bị khác.</p></Modal>}
  </>;
}
function ExcelImport({ mode, onClose }: { mode: 'generic' | 'heda'; onClose: () => void }) {
  const { run } = useApp(); const [sheets, setSheets] = useState<InspectedSheet[]>([]); const [sheetIndex, setSheetIndex] = useState(0); const [fileName, setFileName] = useState(''); const [preview, setPreview] = useState<ImportPreview>(); const [report, setReport] = useState<Awaited<ReturnType<typeof commitGenericImport>>>(); const [busy, setBusy] = useState(false); const [issuePage, setIssuePage] = useState(0);
  const [mapping, setMapping] = useState<ImportMapping>({ date: '', amount: '', type: '', wallet: '', category: '', note: '', time: '', sourceId: '', destination: '', fee: '', dateFormat: 'yyyy-MM-dd', numberFormat: 'plain', currency: 'VND' });
  const sheet = sheets[sheetIndex];
  const action = async (fn: () => Promise<unknown>, success?: string) => { if (busy) return; setBusy(true); try { await run(fn, success); } finally { setBusy(false); } };
  const clearPreview = () => { setPreview(undefined); setReport(undefined); };
  return <Modal title={mode === 'heda' ? 'Phân tích Excel HeDa' : 'Nhập Excel'} onClose={onClose} wide><p className="notice"><ShieldCheck size={18} />File chỉ được đọc trên thiết bị. Không upload lên server.</p>{mode === 'heda' && <p className="body-copy">Chọn file để xem các sheet, header, kiểu dữ liệu và 50 dòng mẫu. Chưa có file HeDa thực tế để xác định quy tắc chuyển đổi. Adapter HeDa phải được xây và đối chiếu từ file nguồn của bạn trước khi nhập lịch sử.</p>}<Field label="Chọn workbook Excel"><input type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (!file) return; void action(async () => { if (file.size > 100000000) throw new Error('File quá lớn (giới hạn 100 MB).'); const result = inspectWorkbook(await file.arrayBuffer()); if (!result.length) throw new Error('Workbook không có sheet.'); setSheets(result); setSheetIndex(0); setFileName(file.name); clearPreview(); setMapping(m => ({ ...m, date: '', amount: '', type: '', wallet: '', category: '', note: '', time: '', sourceId: '', destination: '', fee: '' })); }); e.target.value = ''; }} /></Field>
    {sheet && <><p className="muted">{fileName} · {sheets.length} sheet</p><Field label="Sheet"><select value={sheetIndex} onChange={e => { setSheetIndex(Number(e.target.value)); clearPreview(); }}><option disabled>Chọn sheet</option>{sheets.map((s, i) => <option key={s.name} value={i}>{s.name} · {s.rows.length.toLocaleString()} dòng · {s.headers.length} cột</option>)}</select></Field><div className="table-scroll"><table><thead><tr>{sheet.headers.map(h => <th key={h}>{h}<small>{sheet.types[h].join(' / ')}</small></th>)}</tr></thead><tbody>{sheet.sample.map((row, i) => <tr key={i}>{sheet.headers.map(h => <td key={h}>{String(row[h]).slice(0, 200)}</td>)}</tr>)}</tbody></table></div><p className="footnote">Hiện tối đa 50 dòng mẫu; phân tích kiểu dữ liệu trên 200 dòng đầu. Tổng {sheet.rows.length} dòng trong sheet.</p>
      {mode === 'generic' && !report && <><h3 className="section-subtitle">Chọn ánh xạ cột</h3><p className="footnote">Loại giao dịch hợp lệ: income / expense / transfer / adjustment (hoặc nhãn tiếng Việt tương ứng). Với transfer, chọn thêm ví nhận. Số dư đầu kỳ của ví mới là 0; cần đối chiếu riêng sau import.</p><div className="filter-grid">{([['date', 'Ngày *'], ['amount', 'Số tiền *'], ['type', 'Loại *'], ['wallet', 'Ví *'], ['category', 'Danh mục *'], ['note', 'Ghi chú'], ['time', 'Giờ HH:mm'], ['sourceId', 'ID gốc'], ['destination', 'Ví nhận'], ['fee', 'Phí chuyển khoản']] as const).map(([key, label]) => <Field label={label} key={key}><select value={mapping[key] ?? ''} onChange={e => { setMapping(m => ({ ...m, [key]: e.target.value })); clearPreview(); }}><option value="">Không chọn</option>{sheet.headers.map(h => <option value={h} key={h}>{h}</option>)}</select></Field>)}<Field label="Định dạng ngày"><select value={mapping.dateFormat} onChange={e => { setMapping(m => ({ ...m, dateFormat: e.target.value as ImportMapping['dateFormat'] })); clearPreview(); }}><option value="yyyy-MM-dd">yyyy-MM-dd</option><option value="dd/MM/yyyy">dd/MM/yyyy</option><option value="MM/dd/yyyy">MM/dd/yyyy</option><option value="excel">Excel serial</option></select></Field><Field label="Định dạng số"><select value={mapping.numberFormat} onChange={e => { setMapping(m => ({ ...m, numberFormat: e.target.value as ImportMapping['numberFormat'] })); clearPreview(); }}><option value="plain">Số nguyên (1250000)</option><option value="vi-VN">Việt Nam (1.250.000)</option><option value="en-US">Anh/Mỹ (1,250,000)</option></select></Field></div><button className="button secondary" disabled={busy} onClick={() => void action(async () => { setPreview(await prepareGenericImport(sheet, mapping, fileName)); setIssuePage(0); })}>{busy ? 'Đang kiểm tra…' : 'Kiểm tra & xem trước'}</button></>}
    </>}
    {preview && !report && <section className="import-preview"><h3>Xem trước import</h3><div className="small-metrics"><div><small>Hợp lệ</small><strong>{preview.transactions.length}</strong></div><div><small>Cần kiểm tra</small><strong>{preview.issues.length}</strong></div><div><small>Trùng đã bỏ qua</small><strong>{preview.duplicates}</strong></div></div><p>{preview.wallets.length} ví mới · {preview.categories.length} danh mục mới · {preview.start ?? '—'} → {preview.end ?? '—'}</p><div className="simple-row"><span>Tổng thu</span><Money value={preview.income} /></div><div className="simple-row"><span>Tổng chi (bao gồm phí)</span><Money value={preview.expense} /></div>{preview.issues.length > 0 && <><p className="notice error"><AlertCircle size={18} />Sửa tất cả dòng lỗi trong file rồi chọn lại. Không bỏ qua âm thầm.</p><div className="import-issues">{preview.issues.slice(issuePage * 20, (issuePage + 1) * 20).map((issue, i) => <details key={i}><summary>Dòng {issue.row}: {issue.message}</summary><pre>{issue.raw}</pre></details>)}</div><div className="pagination"><button disabled={!issuePage} className="button secondary" onClick={() => setIssuePage(p => p - 1)}>Trước</button><span>{issuePage + 1} / {Math.ceil(preview.issues.length / 20)}</span><button disabled={(issuePage + 1) * 20 >= preview.issues.length} className="button secondary" onClick={() => setIssuePage(p => p + 1)}>Sau</button></div></>}<button disabled={busy || !!preview.issues.length || !preview.transactions.length} className="button primary submit-button" onClick={() => void action(async () => setReport(await commitGenericImport(preview)), 'Đã import và đối chiếu batch')}>Nhập {preview.transactions.length} giao dịch</button><p className="footnote">Chống trùng ưu tiên ID gốc. Khi không có ID, app so khớp nội dung và số lần xuất hiện: các dòng giống nhau trong cùng file vẫn được giữ đủ. Kiểm tra số trùng trước khi nhập.</p></section>}
    {report && <section className="migration-report"><ShieldCheck size={36} /><h3>Đã nhập & đối chiếu batch</h3><p>✓ {report.count} giao dịch được lưu</p><p>✓ Tổng thu khớp: <Money value={report.income} /></p><p>✓ Tổng chi khớp: <Money value={report.expense} /></p><p>✓ Biến động từng ví khớp với bút toán</p><p>✓ Tham chiếu dữ liệu hợp lệ</p><p className="notice">Báo cáo xác nhận các dòng đã ánh xạ trong batch. Số dư ví nguồn, nợ và toàn bộ lịch sử HeDa chưa được đối chiếu qua importer thông thường.</p><button className="button primary" onClick={onClose}>Hoàn tất</button></section>}
  </Modal>;
}
