import { useEffect, useState, useDeferredValue } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Search, SlidersHorizontal, Plus, X } from 'lucide-react';
import { queryTransactions, type TransactionFilter } from './services';
import { transactionLabels, type TransactionType } from './types';
import { useApp, PageTitle, TransactionRow, EmptyState, Field, Loading } from './ui';

export function Transactions() {
  const { filter: initial, metadata, openTransaction } = useApp();
  const [filter, setFilter] = useState<TransactionFilter>(initial); const [page, setPage] = useState(0); const [advanced, setAdvanced] = useState(false); const search = useDeferredValue(filter.search);
  useEffect(() => { setFilter(initial); setPage(0); }, [initial]);
  const result = useLiveQuery(() => queryTransactions({ ...filter, search }, page), [JSON.stringify(filter), search, page]);
  const change = (next: Partial<TransactionFilter>) => { setFilter(f => ({ ...f, ...next })); setPage(0); };
  const active = Object.entries(filter).filter(([k, v]) => v && k !== 'sort').length;
  return <><PageTitle eyebrow="TỪNG KHOẢN, RÕ RÀNG" title="Giao dịch" description="Tìm lại một khoản chi. Hiểu thêm một thói quen." action={<button className="button primary desktop-only" onClick={() => openTransaction('expense')}><Plus size={18} />Thêm giao dịch</button>} />
    <section className="panel transactions-panel">{filter.reportType && <p className="notice">Đang xem {filter.reportType === 'expense' ? 'chi tiêu và phí chuyển khoản có tính báo cáo' : 'thu nhập có tính báo cáo'}.</p>}<div className="search-toolbar"><label className="search-input"><Search size={20} /><input value={filter.search ?? ''} onChange={e => change({ search: e.target.value })} placeholder="Ghi chú, số tiền, ví, danh mục, người, tag…" aria-label="Tìm giao dịch" />{filter.search && <button className="icon-button" aria-label="Xóa tìm kiếm" onClick={() => change({ search: '' })}><X size={17} /></button>}</label><button className={`button secondary ${advanced ? 'selected' : ''}`} onClick={() => setAdvanced(!advanced)}><SlidersHorizontal size={18} /><span>Bộ lọc{active ? ` (${active})` : ''}</span></button></div>
      <div className="segmented transaction-tabs">{[['', 'Tất cả'], ['expense', 'Chi tiêu'], ['income', 'Thu nhập'], ['transfer', 'Chuyển khoản']].map(([value, label]) => <button key={value} className={(filter.type ?? '') === value ? 'active' : ''} onClick={() => change({ type: value as TransactionType || undefined, reportType: undefined })}>{label}</button>)}</div>
      {advanced && <div className="filter-grid"><Field label="Từ ngày"><input type="date" value={filter.start ?? ''} onChange={e => change({ start: e.target.value || undefined })} /></Field><Field label="Đến ngày"><input type="date" value={filter.end ?? ''} onChange={e => change({ end: e.target.value || undefined })} /></Field><Field label="Loại"><select value={filter.type ?? ''} onChange={e => change({ type: e.target.value as TransactionType || undefined })}><option value="">Tất cả</option>{Object.entries(transactionLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></Field><Field label="Ví"><select value={filter.walletId ?? ''} onChange={e => change({ walletId: e.target.value || undefined })}><option value="">Tất cả ví</option>{metadata.wallets.map(w => <option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><Field label="Danh mục"><select value={filter.categoryId ?? ''} onChange={e => change({ categoryId: e.target.value || undefined })}><option value="">Tất cả danh mục</option>{metadata.categories.map(c => <option key={c.id} value={c.id}>{c.icon} {c.name}</option>)}</select></Field><Field label="Sự kiện"><select value={filter.eventId ?? ''} onChange={e => change({ eventId: e.target.value || undefined })}><option value="">Tất cả</option>{metadata.events.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></Field><Field label="Tag"><select value={filter.tag ?? ''} onChange={e => change({ tag: e.target.value || undefined })}><option value="">Tất cả</option>{metadata.tags.map(t => <option key={t.id} value={t.name}>#{t.name}</option>)}</select></Field><Field label="Thu / chi báo cáo"><select value={filter.reportType ?? ''} onChange={e => change({ reportType: e.target.value as 'income' | 'expense' || undefined })}><option value="">Mọi giao dịch</option><option value="income">Thu nhập báo cáo</option><option value="expense">Chi tiêu & phí báo cáo</option></select></Field><Field label="Sắp xếp"><select value={filter.sort ?? 'newest'} onChange={e => change({ sort: e.target.value as TransactionFilter['sort'] })}><option value="newest">Mới nhất</option><option value="oldest">Cũ nhất</option><option value="largest">Số tiền lớn nhất</option></select></Field><button className="text-link" onClick={() => { setFilter({}); setPage(0); }}>Xóa bộ lọc</button></div>}
      {!result ? <Loading /> : result.rows.length ? <div className="transaction-list">{result.rows.map(tx => <TransactionRow key={tx.id} transaction={tx} />)}</div> : <EmptyState title={active ? 'Không tìm thấy giao dịch' : 'Chưa có giao dịch nào'} description={active ? 'Thử đổi bộ lọc hoặc từ khóa tìm kiếm.' : undefined} action={() => openTransaction('expense')} />}
      {(page > 0 || result?.hasMore) && <div className="pagination"><button className="button secondary" disabled={!page} onClick={() => setPage(p => p - 1)}>Trang trước</button><span>Trang {page + 1}</span><button className="button secondary" disabled={!result?.hasMore} onClick={() => setPage(p => p + 1)}>Trang sau</button></div>}
    </section>
  </>;
}
