import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { Plus, Star, Archive, ArrowUpRight, ArrowLeftRight, Pencil, Trash2, GripVertical, ChevronUp, ChevronDown } from 'lucide-react';
import { db } from './db';
import { id, now, calculateExpression } from './finance';
import { getBalances, saveWallet, deleteWallet, saveCategory, deleteCategory, setWalletArchived, setCategoryArchived } from './services';
import { walletLabels, type Wallet, type WalletType, type Category } from './types';
import { useApp, PageTitle, Money, EmptyState, Modal, Field, SubmitButton, useSubmit, Confirm } from './ui';

export function Wallets() {
  const { metadata, navigate, openTransaction, run } = useApp(); const balances = useLiveQuery(getBalances, [], {} as Record<string, number>);
  const [edit, setEdit] = useState<Wallet | 'new'>(); const [archive, setArchive] = useState(false); const [selected, setSelected] = useState<Wallet>(); const [remove, setRemove] = useState<Wallet>();
  const wallets = metadata.wallets.filter(w => archive || !w.archived);
  return <><PageTitle eyebrow="NƠI GIỮ NHỮNG DỰ ĐỊNH" title="Ví & tài sản" description="Số dư được tính từ số dư đầu kỳ và toàn bộ bút toán." action={<button className="button primary" onClick={() => setEdit('new')}><Plus size={18} />Tạo ví</button>} />
    <div className="list-toolbar"><label className="check-field"><input type="checkbox" checked={archive} onChange={e => setArchive(e.target.checked)} />Hiện ví đã lưu trữ</label><span className="muted">{wallets.length} ví</span></div>
    {!wallets.length ? <section className="panel"><EmptyState title="Tiền của bạn ở đâu?" description="Thêm ví tiền mặt, ngân hàng hoặc ví điện tử để bắt đầu." actionLabel="Tạo ví đầu tiên" action={() => setEdit('new')} /></section> : <div className="wallet-grid">{wallets.map(w => <button className={`wallet-card panel ${w.archived ? 'archived' : ''}`} key={w.id} onClick={() => setSelected(w)}><div className="wallet-top"><span className="wallet-emoji">{w.icon}</span><span>{metadata.settings.defaultWalletId === w.id ? <Star size={17} fill="currentColor" /> : <ArrowUpRight size={19} />}</span></div><h2>{w.name}</h2><span className="muted">{walletLabels[w.type]}{w.archived && ' · Đã lưu trữ'}</span><>{w.balanceVerified === false ? <span className="unverified-balance">Chưa xác minh số dư</span> : <Money value={balances[w.id] ?? w.openingBalance} />}</><small>{w.includeInNetWorth ? 'Tính vào tổng tài sản' : 'Không tính vào tổng tài sản'}</small></button>)}</div>}
    {edit && <WalletForm wallet={edit === 'new' ? undefined : edit} onClose={() => setEdit(undefined)} />}
    {selected && <Modal title={selected.name} onClose={() => setSelected(undefined)}><div className="detail-amount"><span>{selected.balanceVerified === false ? 'Biến động biết được (chưa có số dư gốc)' : 'Số dư sổ sách'}</span><Money value={balances[selected.id] ?? selected.openingBalance} /></div><div className="action-list"><button onClick={() => { navigate('transactions', { walletId: selected.id }); setSelected(undefined); }}><ArrowUpRight size={18} />Lịch sử giao dịch</button><button onClick={() => { setEdit(selected); setSelected(undefined); }}><Pencil size={18} />Chỉnh sửa ví</button>{!selected.archived && <><button onClick={() => { openTransaction('transfer', undefined, selected.id); setSelected(undefined); }}><ArrowLeftRight size={18} />Chuyển tiền từ ví này</button><button onClick={() => { openTransaction('adjustment', undefined, selected.id); setSelected(undefined); }}><ArrowLeftRight size={18} />Điều chỉnh số dư</button><button onClick={async () => { if (await run(() => db.settings.update('app', { defaultWalletId: selected.id }), 'Đã đặt ví mặc định')) setSelected(undefined); }}><Star size={18} />Đặt làm ví mặc định</button></>}<button onClick={async () => { if (await run(() => setWalletArchived(selected.id, !selected.archived), selected.archived ? 'Đã mở lại ví' : 'Đã lưu trữ ví và dừng lịch định kỳ liên quan')) setSelected(undefined); }}><Archive size={18} />{selected.archived ? 'Mở lại ví' : 'Lưu trữ ví'}</button><button className="danger-text" onClick={() => { setRemove(selected); setSelected(undefined); }}><Trash2 size={18} />Xóa ví</button></div></Modal>}
    {remove && <Confirm title="Xóa ví?" message="Chỉ có thể xóa ví chưa được sử dụng. Ví có lịch sử nên được lưu trữ." action={() => deleteWallet(remove.id)} onClose={() => setRemove(undefined)} />}
  </>;
}
function WalletForm({ wallet, onClose }: { wallet?: Wallet; onClose: () => void }) {
  const [name, setName] = useState(wallet?.name ?? ''); const [type, setType] = useState<WalletType>(wallet?.type ?? 'cash'); const [icon, setIcon] = useState(wallet?.icon ?? '💵');
  const [openingBalance, setOpening] = useState(String(wallet?.openingBalance ?? 0)); const [include, setInclude] = useState(wallet?.includeInNetWorth ?? true);
  const { submit, busy } = useSubmit(() => saveWallet({ id: wallet?.id ?? id(), name, type, icon, openingBalance: calculateExpression(openingBalance), currency: 'VND', includeInNetWorth: include, archived: wallet?.archived ?? false, createdAt: wallet?.createdAt ?? now(), balanceVerified: wallet?.balanceVerified }), wallet ? 'Đã cập nhật ví' : 'Đã tạo ví', onClose);
  return <Modal title={wallet ? 'Chỉnh sửa ví' : 'Ví mới'} onClose={onClose}><form onSubmit={submit}><Field label="Tên ví"><input autoFocus required value={name} onChange={e => setName(e.target.value)} placeholder="Ví dụ: Tiền mặt, Vietcombank" /></Field><div className="form-grid"><Field label="Loại ví"><select value={type} onChange={e => setType(e.target.value as WalletType)}>{Object.entries(walletLabels).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></Field><Field label="Biểu tượng"><select value={icon} onChange={e => setIcon(e.target.value)}>{['💵', '🏦', '👛', '🐷', '🌱', '🏠', '💎', '💳'].map(v => <option key={v}>{v}</option>)}</select></Field></div><Field label="Số dư đầu kỳ · VND" hint="Nếu đã có giao dịch, dùng Điều chỉnh số dư thay vì sửa số dư đầu kỳ."><input required inputMode="numeric" value={openingBalance} onChange={e => setOpening(e.target.value)} /></Field><label className="check-field"><input type="checkbox" checked={include} onChange={e => setInclude(e.target.checked)} />Tính vào tổng tài sản</label><SubmitButton busy={busy} label="Lưu ví" /></form></Modal>;
}
export function Categories() {
  const { metadata, run } = useApp(); const [type, setType] = useState<'expense' | 'income'>('expense'); const [edit, setEdit] = useState<Category | 'new'>(); const [selected, setSelected] = useState<Category>(); const [merge, setMerge] = useState(''); const [showArchive, setShowArchive] = useState(false); const [dragged, setDragged] = useState<string>();
  const categories = metadata.categories.filter(c => c.type === type && (showArchive || !c.archived));
  const reorder = async (fromId: string, toId: string) => {
    if (fromId === toId) return; const all = metadata.categories.filter(c => c.type === type); const from = all.findIndex(c => c.id === fromId), to = all.findIndex(c => c.id === toId); if (from < 0 || to < 0) return;
    const next = [...all]; next.splice(to, 0, next.splice(from, 1)[0]);
    await run(() => db.transaction('rw', db.categories, async () => { await db.categories.bulkPut(next.map((c, sortOrder) => ({ ...c, sortOrder }))); }));
  };
  return <><PageTitle eyebrow="SẮP XẾP THEO CÁCH CỦA BẠN" title="Danh mục" action={<button className="button primary" onClick={() => setEdit('new')}><Plus size={18} />Thêm danh mục</button>} /><div className="list-toolbar"><div className="segmented"><button className={type === 'expense' ? 'active' : ''} onClick={() => setType('expense')}>Chi tiêu</button><button className={type === 'income' ? 'active' : ''} onClick={() => setType('income')}>Thu nhập</button></div><label className="check-field"><input type="checkbox" checked={showArchive} onChange={e => setShowArchive(e.target.checked)} />Hiện đã lưu trữ</label></div><section className="panel category-list">{categories.length ? categories.map((c, i) => <div key={c.id} className={`category-management-row ${c.parentId ? 'subcategory' : ''}`} draggable onDragStart={() => setDragged(c.id)} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (dragged) void reorder(dragged, c.id); setDragged(undefined); }}><GripVertical size={18} className="muted" /><button className="category-main" onClick={() => setEdit(c)}><span className="category-icon" style={{ background: `${c.color}20` }}>{c.icon}</span><strong>{c.name}</strong>{c.archived && <small>Đã lưu trữ</small>}</button><button className="icon-button" disabled={i === 0} aria-label={`Di chuyển ${c.name} lên`} onClick={() => void reorder(c.id, categories[i - 1].id)}><ChevronUp size={17} /></button><button className="icon-button" disabled={i === categories.length - 1} aria-label={`Di chuyển ${c.name} xuống`} onClick={() => void reorder(c.id, categories[i + 1].id)}><ChevronDown size={17} /></button><button className="icon-button" aria-label={`Lưu trữ ${c.name}`} onClick={() => void run(() => setCategoryArchived(c.id, !c.archived), c.archived ? 'Đã mở lại danh mục' : 'Đã lưu trữ danh mục và dừng lịch định kỳ liên quan')}><Archive size={17} /></button><button className="icon-button" aria-label={`Xóa ${c.name}`} onClick={() => { setSelected(c); setMerge(''); }}><Trash2 size={17} /></button></div>) : <EmptyState title="Chưa có danh mục" actionLabel="Thêm danh mục" action={() => setEdit('new')} />}</section><p className="footnote">Kéo để sắp xếp trên máy tính; dùng nút lên / xuống trên điện thoại.</p>
    {edit && <CategoryForm type={type} category={edit === 'new' ? undefined : edit} onClose={() => setEdit(undefined)} />}
    {selected && <Modal title="Xóa hoặc gộp danh mục" onClose={() => setSelected(undefined)}><p className="body-copy">Giao dịch được giữ lại. Nếu danh mục đang dùng, chọn danh mục cùng loại để chuyển toàn bộ lịch sử, ngân sách và lịch định kỳ.</p><Field label="Gộp vào"><select value={merge} onChange={e => setMerge(e.target.value)}><option value="">Xóa khi chưa được sử dụng</option>{metadata.categories.filter(c => c.id !== selected.id && c.type === selected.type && !c.archived).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button className="button danger submit-button" onClick={async () => { if (await run(() => deleteCategory(selected.id, merge || undefined), 'Đã xử lý danh mục')) setSelected(undefined); }}>Xác nhận xóa / gộp</button></Modal>}
  </>;
}
function CategoryForm({ type, category, onClose }: { type: 'expense' | 'income'; category?: Category; onClose: () => void }) {
  const { metadata } = useApp(); const [name, setName] = useState(category?.name ?? ''); const [icon, setIcon] = useState(category?.icon ?? '✨'); const [color, setColor] = useState(category?.color ?? '#86a898'); const [parentId, setParent] = useState(category?.parentId ?? '');
  const { submit, busy } = useSubmit(() => saveCategory({ id: category?.id ?? id(), name, type, icon, color, parentId: parentId || undefined, archived: category?.archived ?? false, sortOrder: category?.sortOrder ?? metadata.categories.length }), 'Đã lưu danh mục', onClose);
  return <Modal title={category ? 'Chỉnh sửa danh mục' : 'Danh mục mới'} onClose={onClose}><form onSubmit={submit}><Field label="Tên danh mục"><input value={name} autoFocus required onChange={e => setName(e.target.value)} /></Field><div className="form-grid"><Field label="Biểu tượng"><select value={icon} onChange={e => setIcon(e.target.value)}>{['✨', '🍜', '☕', '🛍️', '🛵', '🏠', '💚', '🎧', '📚', '💼', '🎁', '🌱', '💰', '🐾', '✈️'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Màu"><input type="color" value={color} onChange={e => setColor(e.target.value)} /></Field></div><Field label="Danh mục cha"><select value={parentId} onChange={e => setParent(e.target.value)}><option value="">Không có (danh mục cấp đầu)</option>{metadata.categories.filter(c => c.type === type && !c.parentId && c.id !== category?.id).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><SubmitButton busy={busy} label="Lưu danh mục" /></form></Modal>;
}
